### ISSUE TITLE
No minimum or maximum value

### ISSUE THREAD

**Issue by geekhenno** [burakozyurt/stepper_counter_swipe#1]
How can I set the min value of stepper 1

**Comment by burakozyurt** [comment]
Hello, the minimum value is specified as 0 in the current building. But now
you asked a very logical question. I will deal with this. I will add the
minimum value property.

Almuhanand Ghaleb <notifications@github.com>, 10 Haz 2020 Çar, 15:35
tarihinde şunu yazdı:

**Comment by mybestpalonline** [comment]
How to detect if + is pressed or - is pressed so that we can implement the logic accordingly

**Comment by burakozyurt** [comment]
Okay, i will consider this issue.

12 Haz 2020 Cum 13:54 tarihinde Sarbjit Singh <notifications@github.com>
şunu yazdı:
